### ISSUE TITLE
Installation bumps

### ISSUE THREAD

**Issue by scottcmarks** [OpenMPDK/MacVFN#2] opened 2024-08-06 01:52 UTC
Step 1:
```
git clone -b driverkit https://github.com/baekalfen/xnvme
```
produced
```
fatal: remote error: upload-pack: not our ref 934f84177e4b793a133f914369fdbba98782b150
fatal: Fetched in submodule path 'MacVFN/libvfn', but it did not contain 934f84177e4b793a133f914369fdbba98782b150. Direct fetching of that commit failed.
```
Not going to be denied that quickly, though, so I just decided to route around:
```
scott@Mac-mini-x86 MacVFN $ cat .gitmodules 
[submodule "MacVFN/libvfn"]
	path = MacVFN/libvfn
	url = git@github.com:Baekalfen/libvfn.git
    branch = driverkit
scott@Mac-mini-x86 MacVFN $ cd MacVFN/libvfn
scott@Mac-mini-x86 libvfn $ git checkout driverkit
branch 'driverkit' set up to track 'origin/driverkit'.
Switched to a new branch 'driverkit'
scott@Mac-mini-x86 libvfn $ git fetch --all
scott@Mac-mini-x86 libvfn $ git pull --ff
Already up to date.
scott@Mac-mini-x86 libvfn $ git branch
* driverkit
  main
scott@Mac-mini-x86 libvfn $ ls
AUTHORS			CONTRIBUTORS		LICENSE			ccan			docs			include			lib			meson_options.txt	src			tools
CONTRIBUTING.rst	COPYING			README.rst		config			examples		internal		meson.build		scripts			tests
scott@Mac-mini-x86 libvfn $ pwd
/Users/scott/preboot/MacVFN/MacVFN/libvfn
```
That appeared to be a credible recovery.

But alas, when I tried step 2, I got this:
```
scott@Mac-mini-x86 MacVFN $ make build install kill log
<snip>
/Users/scott/preboot/MacVFN/MacVFN/libvfn/src/pci/util.c:13:10: fatal error: 'byteswap.h' file not found
#include <byteswap.h>
         ^~~~~~~~~~~~
1 error generated.
```
Since this error comes in building ```libvfn```, was I too quick to simply pull the tips of ```driverkit```?  I will investigate in Xcode.  Regardless, the ```.gitmodules``` file for ```MacVFN``` appears to be outdated.

**Comment by Baekalfen** [comment] 2024-09-19 14:38
Sorry, I hadn't seen your PR as I was traveling at the time. Your initial issue should have been fixed now. Maybe that sorts out the second part as well.

**Comment by Baekalfen** [comment] 2024-11-06 12:53
Closed due to inactivity, and assuming the issue is already resolved.

**Closed as completed by Baekalfen** 2024-11-06 12:53 UTC
